In [1]:
import intel_npu_acceleration_library

In [6]:
import numpy as np
import intel_npu_acceleration_library.backend as npu_backend

# Define the decorator
def npu_accelerate(func):
    def wrapper(*args, **kwargs):
        print(f"Running {func.__name__} on Intel NPU...")

        # Convert inputs to NumPy arrays (if they aren't already)
        X, W = [np.asarray(arg, dtype=np.float16) for arg in args]
        
        # Use NPU Backend MatMul function
        matmul = npu_backend.MatMul(X.shape[1], W.shape[0], X.shape[0])
        result = matmul.run(X, W)

        return result
    return wrapper

# Use the decorator for a matrix multiplication function
@npu_accelerate
def matrix_multiply(X, W):
    return np.dot(X, W)  # This will be replaced by the NPU implementation

# Example usage
X = np.random.rand(4, 3).astype(np.float16)  # Batch of 4, 3 features
W = np.random.rand(3, 2).astype(np.float16)  # 3 input channels, 2 output channels

result = matrix_multiply(X, W)
print("Result from NPU:", result)


Running matrix_multiply on Intel NPU...
Result from NPU: [[6.089e-01 8.135e-01 5.418e-05]
 [7.095e-01 7.646e-01 6.539e-05]
 [8.081e-01 7.393e-01 7.886e-05]
 [1.129e+00 9.360e-01 9.787e-05]]


# Basics of oop

In [9]:
from dataclasses import dataclass

@dataclass
class Person:
    name: str
    age: int
    city: str = "Unknown"  # Default value

p = Person(name="Alice", age=30)
print(p)  # Output: Person(name='Alice', age=30, city='Unknown')

Person(name='Alice', age=30, city='Unknown')


In [13]:
import numpy as np

class Activation:

    @staticmethod
    def relu(x):
        """
        Rectified Linear Unit"""
        return max((0,x))

class Neuron:
    def __init__(self, bias, weights,inputs):
        self.bias = bias
        self.weights = weights
        self.inputs = inputs
        self.output = 0

class NeuralLayer:
    def __init__(self, input_layer, size):
        pass
        
        
class NeuralNetwork:
    def __init__(self, input_size =784, hidden_layers=[512,512], output_size=10):
        self.input_size = input_size
        self.hidden_layers = hidden_layers
        self.output_size = output_size
        self.weights = []
        self.biases = []

        # Input to Hidden Layers Network
        self.weights.append(0.01 * np.random.randn(input_size, 
                                                   hidden_layers[0]))
        self.biases.append(np.zeros((1,hidden_layers[0])))
        

        

In [21]:
x = np.linspace(-10,10,100)
y = np.array([Activation.relu(i) for i in x])